spring.application.name=event-gateway
server.port=8080

#FeignClient config url
account.service.url=http://localhost:8081

#Database connection
spring.datasource.url=jdbc:h2:mem:event_gateway_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#jpa 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#h2 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Resilience4j Circuit Breaker
# ==========================
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=3

# ========================S==
# Retry
# ==========================
resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=2s



management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

